apiVersion: apps/v1
kind: Deployment
metadata:
  name: parcel-delivery-system
  labels:
    app: delivery-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-system
  template:
    metadata:
      labels:
        app: delivery-system
    spec:
      containers:
      - name: delivery-system-container
        image: jobanarubi/delivery-system:latest
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-system-service
spec:
  type: NodePort
  selector:
    app: system
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000
